events {
    worker_connections 1024;
}

http {
    upstream portfolio_service {
        server portfolio_service:8000;
    }

    upstream trading_service {
        server trading_service:8001;
    }

    server {
        listen 80;

        location /portfolios {
            proxy_pass http://portfolio_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /trading {
            proxy_pass http://trading_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
