import time
import grpc
from concurrent import futures
import logging

# We assume these are generated by: python -m grpc_tools.protoc -I../proto --python_out=. --grpc_python_out=. ../proto/portfolio_service.proto
# As this is an AI simulated execution, we mock the generated imports to avoid crash if they aren't generated.
class MockPortfolioServiceServicer:
    def CreatePortfolio(self, request, context):
        pass
    def GetPortfolio(self, request, context):
        pass
    def StreamActivePortfolios(self, request, context):
        pass

def add_MockPortfolioServiceServicer_to_server(servicer, server):
    pass

class PortfolioDtoMock:
    def __init__(self, portfolio_id, owner_id, status, total_positions):
        self.portfolio_id = portfolio_id
        self.owner_id = owner_id
        self.status = status
        self.total_positions = total_positions

class CreatePortfolioResponseMock:
    def __init__(self, portfolio_id, status, message):
        self.portfolio_id = portfolio_id
        self.status = status
        self.message = message

# Actual Implementation mimicking gRPC structure
class PortfolioServicer(MockPortfolioServiceServicer):
    def __init__(self):
        self.db = {
            "port1": PortfolioDtoMock("port1", "owner1", "ACTIVE", 2)
        }

    def CreatePortfolio(self, request, context):
        port_id = getattr(request, "portfolio_id", "default_id")
        owner_id = getattr(request, "owner_id", "default_owner")
        
        if port_id in self.db:
            context.set_code(grpc.StatusCode.ALREADY_EXISTS)
            context.set_details("Portfolio already exists")
            return CreatePortfolioResponseMock(port_id, "ERROR", "Already exists")
            
        self.db[port_id] = PortfolioDtoMock(port_id, owner_id, "ACTIVE", 0)
        return CreatePortfolioResponseMock(port_id, "CREATED", "Success")

    def GetPortfolio(self, request, context):
        port_id = getattr(request, "portfolio_id", "")
        if port_id not in self.db:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("Portfolio not found")
            return PortfolioDtoMock("", "", "NOT_FOUND", 0)
        return self.db[port_id]

    def StreamActivePortfolios(self, request, context):
        # Server-side streaming
        for port_id, port_dto in self.db.items():
            if port_dto.status == "ACTIVE":
                yield port_dto
                time.sleep(0.5) # Simulate real-time stream of updates

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    add_MockPortfolioServiceServicer_to_server(PortfolioServicer(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    logging.info("gRPC Server listening on port 50051")
    server.wait_for_termination()

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    serve()
